language: php

php:
    - 7.0
    - 7.1
    - 7.2

branches:
  only:
    - master

install:
    - composer install -n --dev

script:
    - bin/atoum

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover.xml
