language: php

php:
    - 5.5

branches:
  only:
    - master

install:
    - composer install -n --dev

script:
    - bin/atoum

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php occular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
